2020/05/23 07:44:42 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "127.0.0.1:8080"
2020/05/23 07:44:44 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2020/05/23 07:44:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /orders HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "127.0.0.1:8080"
2020/05/23 07:44:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/orders"
2020/05/25 07:22:34 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /orders/list/1/10 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "127.0.0.1:8080"
2020/05/25 19:19:23 [error] 7#7: *1 FastCGI sent in stderr: "PHP message: 2020-05-25T19:19:23+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\OrdersController": argument "$externalDataLoader" of method "__construct()" has type "App\Controller\ExternalDataLoader" but this class was not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /orders/list/1/10 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "127.0.0.1:8080"
